```{r}
<<<<<<< HEAD
library(magrittr)
library(dplyr)
library(ggplot2)
# load("../output/MSPE_pen2_table.Rda")
# load("../output/MSPE_pen3_table.Rda")

MSPE_results <- read.csv("../output/modelsrun_pen2_2.0.csv")
MSPE_results <- as.data.frame(MSPE_results[ which(MSPE_results$V4 >= 10000), -1] )
colnames(MSPE_results) <- c("penalty", "MSPE", "accept", "num_iter")

MSPE_results_THREE <- read.csv("../output/modelsrun_pen3_redo.csv")
=======

# load("../output/MSPE_pen2_table.Rda")
# load("../output/MSPE_pen3_table.Rda")

MSPE_results <- read.csv("../output/modelsrun_pen2.csv")
MSPE_results <- as.data.frame(MSPE_results[ which(MSPE_results$V4 >= 10000), -1] )
colnames(MSPE_results) <- c("penalty", "MSPE", "accept", "num_iter")

MSPE_results_THREE <- read.csv("../output/modelsrun_pen3.csv")
>>>>>>> 8cc3341e4c9336c9a157eb5736a8c32b9c22651a
MSPE_results_THREE <- as.data.frame(MSPE_results_THREE[ which(MSPE_results_THREE$V4 >= 10000), -1] )
colnames(MSPE_results_THREE) <- c("penalty", "MSPE", "accept", "num_iter")


#if models ran at penalty tuning parameter multiple times, average together


MSPE_results2_summ <- MSPE_results %>% 
                        group_by(penalty) %>% 
                        summarise(MSPE = mean(MSPE))


MSPE_results3_summ <- MSPE_results_THREE %>% 
                         # subset(MSPE > 0.0185) %>% 
                        group_by(penalty) %>% 
                        summarise(MSPE = mean(MSPE))

#plot separately 

compare_pen2 <- ggplot(data = MSPE_results2_summ, aes(x = penalty, y = MSPE)) +
  geom_point(aes(x = penalty)) 

plot_pen2 <- compare_pen2 + 
  geom_line() +
<<<<<<< HEAD
  geom_vline( xintercept=-6, col = 'red') + 
  labs(x = expression("Penalty (" ~tau~ "= e^value)")) + 
  ylim(0.017875, 0.017915) +
  xlim(-15, 0) +
  # theme_bw(base_size = 13, base_family = "Helvetica") + 
  theme(text = element_text(size=23),
=======
  geom_vline( xintercept=-23, col = 'red') + 
  xlab("Penalty (e^value)") + 
  xlim(-30, -9) +
  # theme_bw(base_size = 13, base_family = "Helvetica") + 
  theme(text = element_text(size=14),
>>>>>>> 8cc3341e4c9336c9a157eb5736a8c32b9c22651a
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        # panel.background = element_blank(),
        axis.line = element_line(colour = "black")) 


compare_pen3 <- ggplot(data = MSPE_results3_summ, aes(x = penalty, y = MSPE)) +
                  geom_point(aes(x = penalty)) 

plot_pen3 <- compare_pen3 + 
        # ylim(.0185, .0188) + 
        geom_vline( xintercept=-13, col = 'red') + 
        geom_line() +
<<<<<<< HEAD
labs(x = expression("Penalty (" ~tau~ "= e^value)")) + 
  xlim(-30, 0) +
=======
         xlab("Penalty (e^value)") + 
        xlim(-30, -9) +
>>>>>>> 8cc3341e4c9336c9a157eb5736a8c32b9c22651a
        # theme_bw(base_size = 13, base_family = "Helvetica") + 
        theme(text = element_text(size=14),
              panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(),
              # panel.background = element_blank(),
              axis.line = element_line(colour = "black"))  #limits chosen via observation of first plot




print(plot_pen2)
<<<<<<< HEAD
ggsave("MSPE_ISEC2018.pdf")

=======
>>>>>>> 8cc3341e4c9336c9a157eb5736a8c32b9c22651a
print(plot_pen3)

```

```{r}

#want to combine data into one - need column for number of states

MSPE_results2_summ <- MSPE_results2_summ %>% 
                      mutate(states = rep(2, nrow(MSPE_results2_summ)))

MSPE_results3_summ <- MSPE_results3_summ %>% 
                      mutate(states = rep(3, nrow(MSPE_results3_summ)))
  
  
<<<<<<< HEAD
MSPE_results_combined <- rbind(MSPE_results2_summ, MSPE_results3_summ)
=======
MSPE_results_combined <- bind(MSPE_results2_summ, MSPE_results3_summ)
>>>>>>> 8cc3341e4c9336c9a157eb5736a8c32b9c22651a

MSPE_results_combined$states <- as.factor(MSPE_results_combined$states) 
  
#plot with color by model + add vert lines 
          
  compare_1plot <- ggplot(data = MSPE_results_combined, 
                          aes(x = penalty, y = MSPE, 
                              colour = factor(states), group = factor(states))) +
                          geom_point() 
  
  plot_combine <- compare_1plot + 
        scale_colour_manual(name = "States", 
                            breaks = c("2", "3"),
                      values = c("darkblue", "skyblue")) +
        # ylim(.0185, .0188) + 
<<<<<<< HEAD
        geom_vline( xintercept=-3, col = 'skyblue') + 
        geom_vline(xintercept = -6, col = 'darkblue') +
        geom_line(aes(color = states)) +
        labs(x = expression("Penalty (" ~tau~ "= e^value)")) + 
        xlim(-23, 0) +
        # theme_bw(base_size = 13, base_family = "Helvetica") + 
        theme(text = element_text(size=23),
=======
        geom_vline( xintercept=-13, col = 'skyblue') + 
        geom_vline(xintercept = -23, col = 'darkblue') +
        geom_line(aes(color = states)) +
         xlab("Penalty (e^value)") + 
        xlim(-30, 20) +
        # theme_bw(base_size = 13, base_family = "Helvetica") + 
        theme(text = element_text(size=14),
>>>>>>> 8cc3341e4c9336c9a157eb5736a8c32b9c22651a
              panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(),
              # panel.background = element_blank(),
              axis.line = element_line(colour = "black"))  #limits chosen via observation of first plot

  print(plot_combine)
  
    
#Woo done, now save, send to Ephraim, and add to manuscript
ggsave("MSPEcombined_2.0.pdf")
```

