---
title: "R Notebook"
output: html_notebook
---

```{r}
library(mvtnorm)

# set.seed(2018)

load("../data-raw/Colony2_covariate_low_density_4hr.Rda")

covariate.prepped <- prep_inout_data(covariate, delta_t = 1, hours = 4)
betas <- c(.0007, .5, .0005, 0 , 1/4)

simu_cov2 <- sim_pencov_troph(states = 2, time_max = 4*60*60, 
              delta_t = 1, start_state = 1, 
              int_rate = c(.005, .05), num_locations = 1, 
              covariate = covariate.prepped$cov, switch_betas = betas)

path <- "../output/"

```

```{r}
col2_low4 <- read.csv("../data-raw/Colony2_trophallaxis_low_density_4hr.csv")

col2_low4 <- col2_low4[, 1:length(col_names)]
col2_low4 <- col2_low4 %>% 
            tidyr::drop_na()
colnames(col2_low4) <- col_names

col2_low4_5 <- prep_troph_data(col2_low4, hours = 4, delta_t =  5)


Time4 <- 4 * 60 * 60

location <- col2_low4_5$data$Location
start <- col2_low4_5$data$start_time
   # chamber <- chamber


start = start[which(location == 1)]
  

   start <- sort(start)
   int.num <- length(start)
   covariate <- covariate.prepped$cov
  
pdf( file = "../output/Pen2CovPlot.pdf")
 
plot(start, 1:int.num, xlab = "Seconds", ylab = "Cumulative Interaction Count",
     xlim = c(0, Time4))
    points(which(covariate == 0), rep(0, length(which(covariate == 0))), pch = 8, col = "#53bc84")

dev.off()
```


```{r two state}
n_mcmc <- 10000
 tau <- matrix( c(.001, 0, 0, 0, 0,
                  0, .001, 0, 0, 0,
                  0, 0, .01, 0, 0,
                  0, 0,  0, .000000005, 0, 
                  0, 0, 0, 0, .001), nrow = 5, ncol = 5)
# gamma <- c(.005, .005)
X <- simu_cov2$state
 lambda <- c(.005, .05)
start <- list(X = X, lambda = lambda, betas = betas * 1)
i <- exp(-10)

# 
# write.csv(t(c(1, 2, 3, 4)),
#           col.names = c("Penalty", "MSPE", "Accept", "Number of Iterations"),
#           file = "../output/modelsrun_simpencov.csv")


run_model_cov <- DT_pencov_MCMC(penalty = i, starts_data = simu_cov2$inter_persec, 
                        states = 2, ant_file = simu_cov2, chamber = "queen", 
                          hours = 4, a = 1, b = 1, c = 1, d = 1, 
                          tau = tau, tau.pen = 0, n_mcmc = n_mcmc, delta_t = 1,
                          start = start, 
                          data_out =  paste("../data/", "sim_pencov_MCMC", "-", 
                               log(i), "-", n_mcmc, ".csv", sep = ""), 
                        osa_out = paste("../data/", "sim_pencov_OSA", "-", 
                               log(i), "-", n_mcmc, ".csv", sep = ""),
                         modelsrun_out = paste("../output/modelsrun_simpencov.csv", sep=""), 
                          fig_path = path, fig_name = "pencov_MCMC",
                        covariate = (covariate.prepped$cov))


 
```


```{r two state (no cov)}

 gamma <- c(.005, .005)
start <- list(X = X, lambda = lambda, gamma = gamma)


# write.csv(c(1, 2, 3, 4), 
#           row.names = c("Penalty", "MSPE", "Accept", "Number of Iterations"), 
#           file = "../output/modelsrun_simpen2.csv")

run_model_pen2 <- DT_pen_mcmc(penalty = i, starts_data = simu_cov2$inter_persec,
                        states = 2, ant_file = simu_cov2, chamber = "queen",
                        hours = 4, a = 1, b = 1, c = 1, d = 1, 
                        tau = tau, tau.pen = 0, n_mcmc = n_mcmc, 
                        delta_t = 1, start = start,
                        data_out =  paste("../data/", "sim_pen_MCMC", "-",
                               log(i), "-", n_mcmc, ".csv", sep = ""),
                        osa_out = paste("../data/", "pen_OSA", "-",
                               log(i), "-", n_mcmc, ".csv", sep = ""), 
                        modelsrun_out = paste("../output/modelsrun_simpen2.csv", sep=""))

```

```{r pencov diagnoses}



temp_results <- readr::read_csv("../data/sim_pencov_MCMC--10-10000.csv")

path <- "../output/"

#read in data to temp_results

delta_t <- 1
sim_pencov_diag <-  penalty_diagnosis(t(temp_results)[-1, ], 
                               ant_file = simu_cov2,
                              chamber = "queen", states = 2, 
                              Time = 4 * 60 * 60, fig_path = path,
                                fig_name = "pencov_simtest", penalty = log(exp(-10)), 
                              covariate = covariate.prepped$cov)



```


```{r pen diagnoses}



temp_results <- readr::read_csv("../data/sim_pen_MCMC--5-5000.csv")


#read in data to temp_results


sim_pen_diag <-  penalty_diagnosis(t(temp_results)[-1, ], 
                               ant_file = simu_cov2,
                              chamber = "queen", states = 2, 
                              Time = 4 * 60 * 60, fig_path = path,
                                fig_name = "pen_test", penalty = log(exp(-10)))

```
